### ISSUE TITLE
Newest branch's color problem

### ISSUE THREAD

**Issue by Wenzy--** [Looooong/Unity-SRP-VXGI#27]
When i use the " Add Spherical Harmonics pass and environment settings " 's branch,everything is fine except the post process's depth of field is flip.So i import the newest branch base on this branch in the same scene.But I find the color  changed a lot.

The picture above is original.The second one is after import.the lighting looks very flat
![img](https://i.imgur.com/V4foE7u.png)

**Comment by Looooong** [comment]
I suspect a few things:

+ Check Lighting->Environment->Environment Lighting->Intensity Multiplier, change this value to see if it makes any differences.
+ The final color from a light (color multiplied by intensity) is changed from gamma space to linear space. If this is a case, just change the light intensity to match the render result from previous commit. This is because I enabled [`GraphicsSettings.lightsUseLinearIntensity`](https://docs.unity3d.com/ScriptReference/Rendering.GraphicsSettings-lightsUseLinearIntensity.html) by default.

**Comment by Looooong** [comment]
And the latest commit on master branch contains a lot of breaking changes that may transform the lighting result of the scene. Hopefully, I won't have to do this in the future. You probably have to re-check the lighting conditions. That's all.

**Comment by Wenzy--** [comment]
yes,you are right.It's the Intensity Multiplier cause the problem.And in this version, the depth of field is correct now
